version: '3.1'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ./service-account-key.json
      DATABASE_URL: mysql://root:rootpassword@db:3306/video_app
      BUCKET_NAME: test_upload_video_dummy_app
      PROJECT_ID: test_upload_video_dummy_app
      LOCATION: us-central1
      PUBSUB_TOPIC_NAME: your-topic-name

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: video_app
    ports:
      - "33065:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
